spring.application.name=RetrievAI

#gemini related
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.temperature=0.2
#postgresql related
spring.datasource.url=jdbc:postgresql://localhost:5433/retrievai
spring.datasource.username=retrievai
spring.datasource.password=retrievai
#pgvector related
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
#embedding model
spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=768
server.port=8080